#: include DashBoard.kv
#: include FirstScreen.kv

MDNavigationLayout:
  id: nav_layout

  ScreenManager:

    Screen:

      BoxLayout:
        orientation: 'vertical'

        MDTopAppBar:
          title: app.title
          elevation: 10
          

        ScreenManager:
          id: screen_manager

          DashBoard:
            id: dashboard
            name: "dashboard"

          FirstScreen:
            id: first_screen
            name: "first_screen"

  MDNavigationDrawer:
